# Generated by Django 5.0.4 on 2024-04-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('points', models.IntegerField()),
                ('special', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.movement')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('health', models.IntegerField()),
                ('physical_attack', models.IntegerField()),
                ('physical_defence', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defence', models.IntegerField()),
                ('gen1_special', models.IntegerField(blank=True)),
                ('movement', models.ManyToManyField(through='pokemon.Perlevel', to='pokemon.movement')),
            ],
        ),
        migrations.AddField(
            model_name='perlevel',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon'),
        ),
    ]
